# Site settings
title: High Five, Good Job
header-img: img/home-bg.png
email: kate.mchugh94@gmail.com
copyright_name: KateMchughWestfall94
description: > # this means to ignore newlines until "baseurl:"
  My Journey Into Full Stack Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KateMchughWestfall94
learn_profile: KateMchughWestfall94
email_username: kate.mchugh94@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
